[2024-12-14T05:48:31.990-0800] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-14T05:48:31.999-0800] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ex_python_operator.Transform scheduled__2024-12-13T00:00:00+00:00 [queued]>
[2024-12-14T05:48:32.005-0800] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ex_python_operator.Transform scheduled__2024-12-13T00:00:00+00:00 [queued]>
[2024-12-14T05:48:32.005-0800] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-14T05:48:32.016-0800] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): Transform> on 2024-12-13 00:00:00+00:00
[2024-12-14T05:48:32.023-0800] {standard_task_runner.py:72} INFO - Started process 11142 to run task
[2024-12-14T05:48:32.030-0800] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'ex_python_operator', 'Transform', 'scheduled__2024-12-13T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/Python_operator_dag.py', '--cfg-path', '/var/folders/05/fw9xrgzd2xz986svxp5_g00w0000gn/T/tmplkc8moam']
[2024-12-14T05:48:32.034-0800] {standard_task_runner.py:105} INFO - Job 5: Subtask Transform
[2024-12-14T05:48:32.096-0800] {task_command.py:467} INFO - Running <TaskInstance: ex_python_operator.Transform scheduled__2024-12-13T00:00:00+00:00 [running]> on host rishus-macbook-pro.local
[2024-12-14T05:48:32.163-0800] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ex_python_operator' AIRFLOW_CTX_TASK_ID='Transform' AIRFLOW_CTX_EXECUTION_DATE='2024-12-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-13T00:00:00+00:00'
[2024-12-14T05:48:32.165-0800] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-14T05:48:32.165-0800] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-14T05:48:32.166-0800] {logging_mixin.py:190} INFO - Current task name:Transform state:running start_date:2024-12-14 13:48:32.000200+00:00
[2024-12-14T05:48:32.167-0800] {logging_mixin.py:190} INFO - Dag name:ex_python_operator and current dag run status:running
[2024-12-14T05:48:32.167-0800] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-14T05:48:32.169-0800] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: transform() takes 0 positional arguments but 1 was given
[2024-12-14T05:48:32.179-0800] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-14T05:48:32.180-0800] {logging_mixin.py:190} INFO - Task start:2024-12-14 13:48:32.000200+00:00 end:2024-12-14 13:48:32.178838+00:00 duration:0.178638
[2024-12-14T05:48:32.181-0800] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): Transform> dag:<DAG: ex_python_operator> dagrun:<DagRun ex_python_operator @ 2024-12-13 00:00:00+00:00: scheduled__2024-12-13T00:00:00+00:00, state:running, queued_at: 2024-12-14 13:48:15.668368+00:00. externally triggered: False>
[2024-12-14T05:48:32.182-0800] {logging_mixin.py:190} INFO - Failure caused by transform() takes 0 positional arguments but 1 was given
[2024-12-14T05:48:32.184-0800] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=ex_python_operator, task_id=Transform, run_id=scheduled__2024-12-13T00:00:00+00:00, execution_date=20241213T000000, start_date=20241214T134832, end_date=20241214T134832
[2024-12-14T05:48:32.195-0800] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-14T05:48:32.196-0800] {standard_task_runner.py:124} ERROR - Failed to execute job 5 for task Transform (transform() takes 0 positional arguments but 1 was given; 11142)
Traceback (most recent call last):
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: transform() takes 0 positional arguments but 1 was given
[2024-12-14T05:48:32.212-0800] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-14T05:48:32.243-0800] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-14T05:48:32.248-0800] {local_task_job_runner.py:245} INFO - ::endgroup::
